### ISSUE TITLE
map descriptor empty

### ISSUE THREAD

**Issue by vilzio89** [Another-Axiom/GT_CustomMapExample#17]
i downloaded the latest release by clicking code > download zip and the map descriptor is empty

**Comment by vilzio89** [comment]
i downloaded v0.5 even though it says pre release because its the only way to export if map descriptor is broken in "v1.0" how is that a full release

**Comment by tgeorge-fxp** [comment]
Apologies, there was a missed file in the upload. Please try again with [Release v1.1](https://github.com/Another-Axiom/GT_CustomMapExample/releases/tag/v1.1).
