### ISSUE TITLE
why is my MapDescriptor empty?

### ISSUE THREAD

**Issue by Danik4ek** [Another-Axiom/GT_CustomMapExample#19]
![image](https://github.com/user-attachments/assets/f1922723-d058-4d5e-9019-1bb9bf339f75)
I tried to use a template and an empty scene, the descriptor is just empty everywhere

**Comment by tgeorge-fxp** [comment]
Apologies, there was a missed file in the upload. Please try again with [Release v1.1](https://github.com/Another-Axiom/GT_CustomMapExample/releases/tag/v1.1).
