### ISSUE TITLE
Most of the probuilder and tmp issues were fixed but there are still some unallowed components preventing their use

### ISSUE THREAD

**Issue by Nokoksu** [Another-Axiom/GT_CustomMapExample#20]
Such as RectTransforms and ProBuilderShapes
![Screenshot_451](https://github.com/user-attachments/assets/52711d3e-64ae-4daf-ae30-3a7a9581caa8)

**Comment by echotyler** [comment]
SpriteRenderers and BillboardRenderers are disallowed for some reason too

**Comment by tgeorge-fxp** [comment]
[Release v1.2](https://github.com/Another-Axiom/GT_CustomMapExample/releases/tag/v1.2) should fix these issues. Thanks for the report!
