### ISSUE TITLE
Water isn`t working

### ISSUE THREAD

**Issue by Danik4ek** [Another-Axiom/GT_CustomMapExample#21]
Why doesn't my water work, I'm drowning in it more slowly, but I can't push myself with my hands. And also, how to make ropes and cables?

**Comment by tgeorge-fxp** [comment]
Water Volumes should be fixed with today's (Oct 23, 2024) Gorilla Tag hotfix. Ropes and Ziplines aren't currently supported on Custom Maps, but they are planned additions for future updates. Thanks for the report!
