### ISSUE TITLE
Ability to change in game code?

### ISSUE THREAD

**Issue by luxraygtag** [Another-Axiom/GT_CustomMapExample#4]
I am currently making a moon map, and I don't think I can change the gravity threshold in the unity project. Would it be possible (or even allowed) to change in game code via the GT Object Placeholder script to allow such functionality?

**Comment by luxraygtag** [comment]
I also though about using a force object, but I'm sure being in one removes gravity.

**Comment by lunakittyyy** [comment]
Assetbundles cannot directly contain scripts so this is either not possible or very hard to implement
