### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by sussyboy123** [Another-Axiom/GT_CustomMapExample#6]
Can we put scripts in the custom map for like making working door, minigame, etc

plus this repo need a discussion tab

**Comment by developer9998** [comment]
Custom scripts are not included with this project. The repository references the Gorilla Tag Modding Discord numerous times which can be used for discussion and distribution of maps / levels.

**Comment by sussyboy123** [comment]
> Custom scripts are not included with this project. The repository references the Gorilla Tag Modding Discord numerous times which can be used for discussion and distribution of maps / levels.

oh ok thanks
