### ISSUE TITLE
uhh is probuilder supported?

### ISSUE THREAD

**Issue by bubzilla** [Another-Axiom/GT_CustomMapExample#7]
sorry if my question is a bit dumb im kinda a unity noob lmao

**Comment by bubzilla** [comment]
oh yeah and also textmeshpro

**Comment by luxraygtag** [comment]
I used probuilder for mine. Just use the surface override script for sounds, and add mesh colliders, and you should be all good.

**Comment by bubzilla** [comment]
goated :D
